#ifndef EXT4_FFI_H
#define EXT4_FFI_H

/* Generated by cbindgen from crates/ext4-ffi. Do not edit. */

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/**
 * File types (same values as ext4 directory entry types).
 */
#define EXT4_FT_UNKNOWN 0

#define EXT4_FT_REG 1

#define EXT4_FT_DIR 2

#define EXT4_FT_CHR 3

#define EXT4_FT_BLK 4

#define EXT4_FT_FIFO 5

#define EXT4_FT_SOCK 6

#define EXT4_FT_LNK 7

#define UF_NODUMP 1

#define UF_IMMUTABLE 2

#define UF_APPEND 4

/**
 * Bits of [`Ext4SetAttr::valid`].
 */
#define EXT4_SET_MODE (1 << 0)

#define EXT4_SET_UID (1 << 1)

#define EXT4_SET_GID (1 << 2)

#define EXT4_SET_SIZE (1 << 3)

#define EXT4_SET_ATIME (1 << 4)

#define EXT4_SET_MTIME (1 << 5)

#define EXT4_SET_CTIME (1 << 6)

#define EXT4_SET_CRTIME (1 << 7)

#define EXT4_SET_BSD_FLAGS (1 << 8)

/**
 * Result of probing a device.
 */
#define EXT4_SUPPORT_READ_WRITE 0

#define EXT4_SUPPORT_READ_ONLY 1

#define EXT4_SUPPORT_UNSUPPORTED 2

/**
 * Rename flags.
 */
#define EXT4_RENAME_NOREPLACE 1

#define EXT4_RENAME_EXCHANGE 2

/**
 * xattr set modes.
 */
#define EXT4_XATTR_ANY 0

#define EXT4_XATTR_CREATE 1

#define EXT4_XATTR_REPLACE 2

typedef struct Ext4Handle Ext4Handle;

/**
 * Log sink: `level` is error=1 … trace=5, `msg` is NUL-terminated.
 */
typedef void (*Ext4LogCallback)(int32_t level, const char *msg);

/**
 * Block device callbacks. All callbacks return 0 or a Darwin errno.
 */
typedef struct Ext4DeviceOps {
  void *ctx;
  int32_t (*read)(void *ctx, uint64_t offset, uint8_t *buf, size_t len);
  int32_t (*write)(void *ctx, uint64_t offset, const uint8_t *buf, size_t len);
  int32_t (*flush)(void *ctx);
  /**
   * Called once when the device is no longer used (may be null).
   */
  void (*release)(void *ctx);
  /**
   * Device size in bytes.
   */
  uint64_t size;
  /**
   * Required I/O alignment (physical block size); 0 means 512.
   */
  uint32_t sector_size;
  bool read_only;
} Ext4DeviceOps;

typedef struct Ext4ProbeInfo {
  /**
   * NUL-terminated volume label (UTF-8, may be empty).
   */
  uint8_t label[17];
  uint8_t uuid[16];
  uint32_t block_size;
  uint64_t blocks;
  /**
   * One of the `EXT4_SUPPORT_*` values.
   */
  int32_t support;
  /**
   * Whether the journal needs recovery (volume was not cleanly unmounted).
   */
  bool needs_recovery;
  /**
   * Whether the file system has an internal journal.
   */
  bool has_journal;
  /**
   * 0 = ext2, 1 = ext3, 2 = ext4 (by feature set).
   */
  uint8_t subtype;
} Ext4ProbeInfo;

typedef struct Ext4MountOptions {
  bool read_only;
  /**
   * Metadata cache size in blocks (0 = default).
   */
  uint32_t cache_blocks;
  /**
   * Seconds between automatic commits (0 = default 5 s).
   */
  uint32_t commit_interval_secs;
  /**
   * Keep unlinked inodes until `ext4_reclaim` (true for FSKit).
   */
  bool defer_unlinked;
} Ext4MountOptions;

typedef struct Ext4StatFs {
  uint32_t block_size;
  uint64_t blocks;
  uint64_t free_blocks;
  uint64_t avail_blocks;
  uint64_t files;
  uint64_t free_files;
  uint32_t name_max;
} Ext4StatFs;

typedef struct Ext4Time {
  int64_t sec;
  uint32_t nsec;
} Ext4Time;

typedef struct Ext4Attr {
  uint32_t ino;
  /**
   * One of the `EXT4_FT_*` values.
   */
  uint8_t file_type;
  bool has_crtime;
  /**
   * Full mode including the file type bits.
   */
  uint16_t mode;
  uint32_t nlink;
  uint32_t uid;
  uint32_t gid;
  uint64_t size;
  uint64_t allocated;
  struct Ext4Time atime;
  struct Ext4Time mtime;
  struct Ext4Time ctime;
  struct Ext4Time crtime;
  /**
   * ext4 inode flags (`EXT4_*_FL`).
   */
  uint32_t flags;
  /**
   * BSD file flags derived from the ext4 flags (UF_IMMUTABLE, ...).
   */
  uint32_t bsd_flags;
  uint32_t generation;
  /**
   * Darwin dev_t for device nodes.
   */
  uint32_t rdev;
} Ext4Attr;

/**
 * Directory entry callback: return false to stop. `attr` is null unless
 * attributes were requested.
 */
typedef bool (*Ext4DirCallback)(void *ctx,
                                const uint8_t *name,
                                size_t len,
                                uint32_t ino,
                                uint8_t file_type,
                                uint64_t next_cookie,
                                const struct Ext4Attr *attr);

typedef struct Ext4SetAttr {
  uint32_t valid;
  /**
   * Permission bits (file type bits are ignored).
   */
  uint16_t mode;
  uint32_t uid;
  uint32_t gid;
  uint64_t size;
  struct Ext4Time atime;
  struct Ext4Time mtime;
  struct Ext4Time ctime;
  struct Ext4Time crtime;
  uint32_t bsd_flags;
} Ext4SetAttr;

/**
 * Extent callback for [`ext4_map_for_io`]: offsets and length in bytes;
 * `zero_fill` extents have no device location. Return false to stop.
 */
typedef bool (*Ext4ExtentCallback)(void *ctx,
                                   uint64_t logical,
                                   uint64_t physical,
                                   uint64_t length,
                                   bool zero_fill);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Route library log messages (error=1 … trace=5) to `cb`. Call once.
 */
void ext4_set_log_callback(Ext4LogCallback cb);

/**
 * Library version as a NUL-terminated string.
 */
const char *ext4_version(void);

/**
 * Check whether a device holds an ext2/3/4 file system.
 * Returns 0 and fills `out` if it does, `EINVAL`/`EIO` otherwise.
 * The device's `release` callback is not called.
 *
 * # Safety
 * `ops` must be valid; `out` must be valid for writes.
 */
int32_t ext4_probe(const struct Ext4DeviceOps *ops, struct Ext4ProbeInfo *out);

/**
 * Mount the file system. On success `*out` receives a handle to release
 * with [`ext4_close`]. The device's `release` callback runs when the
 * handle is closed (or immediately if mounting fails).
 *
 * # Safety
 * `ops` and `opts` must be valid (opts may be null); `out` valid for write.
 */
int32_t ext4_mount(const struct Ext4DeviceOps *ops,
                   const struct Ext4MountOptions *opts,
                   struct Ext4Handle **out);

/**
 * Commit and mark the file system clean, keeping the volume open
 * read-only (for FSKit's unmount, which is followed by reclaims).
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_finish(const struct Ext4Handle *h);

/**
 * Make a volume closed with [`ext4_finish`] writable again.
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_remount(const struct Ext4Handle *h);

/**
 * Flush everything and mark the file system clean. The handle stays
 * allocated (further calls fail with EBUSY) until [`ext4_close`].
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_unmount(const struct Ext4Handle *h);

/**
 * Release a handle (unmounting first if needed).
 *
 * # Safety
 * `h` must come from [`ext4_mount`] and not be used afterwards.
 */
void ext4_close(struct Ext4Handle *h);

/**
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_sync(const struct Ext4Handle *h);

/**
 * # Safety
 * `h` must be a live handle.
 */
bool ext4_is_read_only(const struct Ext4Handle *h);

/**
 * Volume label/UUID/geometry of a mounted volume.
 *
 * # Safety
 * `h` must be a live handle; `out` valid for writes.
 */
int32_t ext4_volume_info(const struct Ext4Handle *h, struct Ext4ProbeInfo *out);

/**
 * # Safety
 * `h` must be a live handle; `out` valid for writes.
 */
int32_t ext4_statfs(const struct Ext4Handle *h, struct Ext4StatFs *out);

/**
 * Change the volume label (at most 16 bytes).
 *
 * # Safety
 * `h` must be a live handle; `name` valid for `len` bytes.
 */
int32_t ext4_set_label(const struct Ext4Handle *h, const uint8_t *name, size_t len);

/**
 * # Safety
 * `h` must be a live handle; `out` valid for writes.
 */
int32_t ext4_stat(const struct Ext4Handle *h, uint32_t ino, struct Ext4Attr *out);

/**
 * # Safety
 * `h` must be a live handle; `name` valid for `len` bytes; `out` valid.
 */
int32_t ext4_lookup(const struct Ext4Handle *h,
                    uint32_t dir,
                    const uint8_t *name,
                    size_t len,
                    struct Ext4Attr *out);

/**
 * Enumerate a directory from `cookie` (0 = start). "." and ".." are
 * included unless `skip_dots`. With `want_attrs`, every entry carries its
 * attributes.
 *
 * # Safety
 * `h` must be a live handle; `cb` must not call into this library.
 */
int32_t ext4_readdir(const struct Ext4Handle *h,
                     uint32_t dir,
                     uint64_t cookie,
                     bool skip_dots,
                     bool want_attrs,
                     Ext4DirCallback cb,
                     void *ctx);

/**
 * # Safety
 * `h` must be a live handle; `buf` valid for `len` bytes.
 */
int32_t ext4_read(const struct Ext4Handle *h,
                  uint32_t ino,
                  uint64_t offset,
                  uint8_t *buf,
                  size_t len,
                  size_t *nread);

/**
 * # Safety
 * `h` must be a live handle; `buf` valid for `len` bytes.
 */
int32_t ext4_write(const struct Ext4Handle *h,
                   uint32_t ino,
                   uint64_t offset,
                   const uint8_t *buf,
                   size_t len,
                   size_t *nwritten);

/**
 * Create a node of type `file_type` (regular, fifo, socket, char/block
 * device) or a directory (`EXT4_FT_DIR`).
 *
 * # Safety
 * `h` must be a live handle; `name` valid for `len` bytes; `out` valid.
 */
int32_t ext4_create(const struct Ext4Handle *h,
                    uint32_t dir,
                    const uint8_t *name,
                    size_t len,
                    uint8_t file_type,
                    uint16_t perm,
                    uint32_t uid,
                    uint32_t gid,
                    uint32_t rdev,
                    struct Ext4Attr *out);

/**
 * # Safety
 * `h` must be a live handle; pointers valid for their lengths.
 */
int32_t ext4_symlink(const struct Ext4Handle *h,
                     uint32_t dir,
                     const uint8_t *name,
                     size_t len,
                     const uint8_t *target,
                     size_t target_len,
                     uint32_t uid,
                     uint32_t gid,
                     struct Ext4Attr *out);

/**
 * Copy a symlink target into `buf` (`ERANGE` if `cap` is too small;
 * `*len` receives the full length either way).
 *
 * # Safety
 * `h` must be a live handle; `buf` valid for `cap` bytes.
 */
int32_t ext4_readlink(const struct Ext4Handle *h,
                      uint32_t ino,
                      uint8_t *buf,
                      size_t cap,
                      size_t *len);

/**
 * # Safety
 * `h` must be a live handle; `name` valid for `len` bytes; `out` valid.
 */
int32_t ext4_link(const struct Ext4Handle *h,
                  uint32_t ino,
                  uint32_t dir,
                  const uint8_t *name,
                  size_t len,
                  struct Ext4Attr *out);

/**
 * Remove a name (file or empty directory). The inode itself is released
 * by [`ext4_reclaim`] once no longer referenced.
 *
 * # Safety
 * `h` must be a live handle; `name` valid for `len` bytes.
 */
int32_t ext4_remove(const struct Ext4Handle *h, uint32_t dir, const uint8_t *name, size_t len);

/**
 * # Safety
 * `h` must be a live handle; names valid for their lengths.
 */
int32_t ext4_rename(const struct Ext4Handle *h,
                    uint32_t src_dir,
                    const uint8_t *src_name,
                    size_t src_len,
                    uint32_t dst_dir,
                    const uint8_t *dst_name,
                    size_t dst_len,
                    uint32_t flags);

/**
 * # Safety
 * `h` must be a live handle; `attr` valid; `out` valid for writes.
 */
int32_t ext4_setattr(const struct Ext4Handle *h,
                     uint32_t ino,
                     const struct Ext4SetAttr *attr,
                     struct Ext4Attr *out);

/**
 * The kernel dropped its last reference to `ino`.
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_reclaim(const struct Ext4Handle *h, uint32_t ino);

/**
 * Preallocate `[offset, offset+len)`.
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_fallocate(const struct Ext4Handle *h,
                       uint32_t ino,
                       uint64_t offset,
                       uint64_t len,
                       bool keep_size);

/**
 * Deallocate `[offset, offset+len)`, keeping the size.
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_punch_hole(const struct Ext4Handle *h, uint32_t ino, uint64_t offset, uint64_t len);

/**
 * Byte offset just past the last allocated block of a file (its
 * "physical end of file", including preallocated blocks past EOF).
 *
 * # Safety
 * `h` must be a live handle; `out` valid for writes.
 */
int32_t ext4_allocated_end(const struct Ext4Handle *h, uint32_t ino, uint64_t *out);

/**
 * SEEK_DATA (`data = true`) / SEEK_HOLE from `offset`.
 *
 * # Safety
 * `h` must be a live handle; `out` valid for writes.
 */
int32_t ext4_seek(const struct Ext4Handle *h,
                  uint32_t ino,
                  uint64_t offset,
                  bool data,
                  uint64_t *out);

/**
 * Map a file range for kernel offloaded I/O. For writes, missing blocks
 * are allocated as unwritten; report completion with
 * [`ext4_complete_write`].
 *
 * # Safety
 * `h` must be a live handle; `cb` must not call into this library.
 */
int32_t ext4_map_for_io(const struct Ext4Handle *h,
                        uint32_t ino,
                        uint64_t offset,
                        uint64_t len,
                        bool write,
                        Ext4ExtentCallback cb,
                        void *ctx);

/**
 * The kernel finished writing `[offset, offset+len)` of `ino` directly.
 *
 * # Safety
 * `h` must be a live handle.
 */
int32_t ext4_complete_write(const struct Ext4Handle *h,
                            uint32_t ino,
                            uint64_t offset,
                            uint64_t len);

/**
 * Read xattr `name` (macOS naming). With `buf == NULL` only the size is
 * returned in `*len`.
 *
 * # Safety
 * `h` must be a live handle; pointers valid for their lengths.
 */
int32_t ext4_getxattr(const struct Ext4Handle *h,
                      uint32_t ino,
                      const uint8_t *name,
                      size_t name_len,
                      uint8_t *buf,
                      size_t cap,
                      size_t *len);

/**
 * # Safety
 * `h` must be a live handle; pointers valid for their lengths.
 */
int32_t ext4_setxattr(const struct Ext4Handle *h,
                      uint32_t ino,
                      const uint8_t *name,
                      size_t name_len,
                      const uint8_t *value,
                      size_t value_len,
                      uint32_t mode);

/**
 * # Safety
 * `h` must be a live handle; `name` valid for `name_len` bytes.
 */
int32_t ext4_removexattr(const struct Ext4Handle *h,
                         uint32_t ino,
                         const uint8_t *name,
                         size_t name_len);

/**
 * List visible xattr names as NUL-terminated strings back to back.
 * With `buf == NULL` only the size is returned.
 *
 * # Safety
 * `h` must be a live handle; `buf` valid for `cap` bytes.
 */
int32_t ext4_listxattr(const struct Ext4Handle *h,
                       uint32_t ino,
                       uint8_t *buf,
                       size_t cap,
                       size_t *len);

/**
 * Validate a name as ext4 would (for early rejection in Swift).
 *
 * # Safety
 * `name` valid for `len` bytes.
 */
int32_t ext4_validate_name(const uint8_t *name, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EXT4_FFI_H */
